In [16]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
df = pd.read_csv("Churn_Modelling.csv")

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
df = df.drop("Surname", axis=1)
df = df.drop("RowNumber", axis=1)
df = df.drop("CustomerId", axis=1)

In [5]:
df = pd.get_dummies(df)

In [6]:
x = df.drop("Exited", axis=1)

In [7]:
y = df["Exited"]

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [9]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [10]:
model = Sequential()

In [11]:
x_train.shape[1]

13

In [12]:
model.add(Dense(128, activation='relu', input_shape =(x_train.shape[1],)))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               1792      
                                                                 
 dense_1 (Dense)             (None, 64)                8256      
                                                                 
 dense_2 (Dense)             (None, 1)                 65        
                                                                 
Total params: 10113 (39.50 KB)
Trainable params: 10113 (39.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [15]:
model.fit(x_train, y_train, epochs=20, batch_size=32, verbose=1)

Epoch 1/20
250/250 [==============================] - 1s 1ms/step - loss: 0.4314 - accuracy: 0.8163
Epoch 2/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3635 - accuracy: 0.8487
Epoch 3/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3456 - accuracy: 0.8595
Epoch 4/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3392 - accuracy: 0.8596
Epoch 5/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3348 - accuracy: 0.8625
Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3325 - accuracy: 0.8643
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3290 - accuracy: 0.8625
Epoch 8/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3259 - accuracy: 0.8651
Epoch 9/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3229 - accuracy: 0.8664
Epoch 10/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3199 - accuracy: 0.8664

In [17]:
y_pred = model.predict(x_test)

63/63 [==============================] - 0s 1ms/step


In [18]:
y_pred

array([[0.02352443],
       [0.00560685],
       [0.10315914],
       ...,
       [0.6898291 ],
       [0.037676  ],
       [0.20047505]], dtype=float32)

In [19]:
y_pred = (y_pred > 0.5)

In [20]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [ True],
       [False],
       [False]])

In [21]:
accuracy_score = accuracy_score(y_test, y_pred)

In [22]:
cm = confusion_matrix(y_test, y_pred)

In [23]:
accuracy_score

0.8565

In [24]:
cm

array([[1551,   56],
       [ 231,  162]], dtype=int64)